# Generated by Django 4.2.30 on 2026-06-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=340, unique=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('album_type', models.CharField(choices=[('studio', 'Estudio'), ('live', 'En vivo'), ('compilation', 'Compilación'), ('ep', 'EP'), ('single', 'Single')], default='studio', max_length=20)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['artist', '-release_year'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('artist_type', models.CharField(choices=[('solo', 'Solista'), ('orchestra', 'Orquesta / Conjunto')], default='solo', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('formed_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disbanded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='catalog.country')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=340, unique=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='songs', to='catalog.genre')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveSmallIntegerField()),
                ('disc_number', models.PositiveSmallIntegerField(default=1)),
                ('duration_override', models.PositiveIntegerField(blank=True, help_text='Duración en segundos (sobreescribe la de la canción)', null=True)),
                ('is_bonus', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
                'ordering': ['disc_number', 'track_number'],
                'unique_together': {('album', 'disc_number', 'track_number')},
            },
        ),
        migrations.CreateModel(
            name='SongCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('composer', 'Compositor'), ('lyricist', 'Letrista'), ('arranger', 'Arreglista'), ('producer', 'Productor'), ('engineer', 'Ingeniero'), ('vocalist', 'Vocalista'), ('instrumentalist', 'Instrumentista'), ('conductor', 'Director')], max_length=20)),
                ('instrument', models.CharField(blank=True, max_length=100)),
                ('as_name', models.CharField(blank=True, help_text='Nombre acreditado si difiere del nombre real', max_length=200)),
                ('credited_on_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_credits', to='catalog.track')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['role', 'person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='catalog.country')),
            ],
            options={
                'verbose_name': 'Sello discográfico',
                'verbose_name_plural': 'Sellos discográficos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrchestraMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('instrument', models.CharField(blank=True, max_length=100)),
                ('join_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('leave_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='catalog.artist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestra_memberships', to='catalog.person')),
            ],
            options={
                'verbose_name': 'Miembro de orquesta',
                'verbose_name_plural': 'Miembros de orquesta',
                'ordering': ['person__full_name'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='catalog.country'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='record_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='catalog.recordlabel'),
        ),
    ]
